// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/oapivalidator (interfaces: Authenticator,FailureHandler)
//
// Generated by this command:
//
//	mockgen -destination mocks/interfaces.gen.go -package mocks . Authenticator,FailureHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	oapivalidator "github.com/devctllabs/go-libs/oapivalidator"
	echo "github.com/labstack/echo/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticator) Authenticate(ctx context.Context, input oapivalidator.AuthenticationInput) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, input)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticatorMockRecorder) Authenticate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticator)(nil).Authenticate), ctx, input)
}

// MockFailureHandler is a mock of FailureHandler interface.
type MockFailureHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFailureHandlerMockRecorder
	isgomock struct{}
}

// MockFailureHandlerMockRecorder is the mock recorder for MockFailureHandler.
type MockFailureHandlerMockRecorder struct {
	mock *MockFailureHandler
}

// NewMockFailureHandler creates a new mock instance.
func NewMockFailureHandler(ctrl *gomock.Controller) *MockFailureHandler {
	mock := &MockFailureHandler{ctrl: ctrl}
	mock.recorder = &MockFailureHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailureHandler) EXPECT() *MockFailureHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFailureHandler) Handle(c *echo.Context, failure *oapivalidator.Failure) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", c, failure)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockFailureHandlerMockRecorder) Handle(c, failure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFailureHandler)(nil).Handle), c, failure)
}
