// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=store.gen_test.go -package=oidcsessionredis -typed
//

// Package oidcsessionredis is a generated GoMock package.
package oidcsessionredis

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MocksessionStore is a mock of sessionStore interface.
type MocksessionStore struct {
	ctrl     *gomock.Controller
	recorder *MocksessionStoreMockRecorder
	isgomock struct{}
}

// MocksessionStoreMockRecorder is the mock recorder for MocksessionStore.
type MocksessionStoreMockRecorder struct {
	mock *MocksessionStore
}

// NewMocksessionStore creates a new mock instance.
func NewMocksessionStore(ctrl *gomock.Controller) *MocksessionStore {
	mock := &MocksessionStore{ctrl: ctrl}
	mock.recorder = &MocksessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionStore) EXPECT() *MocksessionStoreMockRecorder {
	return m.recorder
}

// CommitRefresh mocks base method.
func (m *MocksessionStore) CommitRefresh(ctx context.Context, params refreshCommitParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitRefresh", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitRefresh indicates an expected call of CommitRefresh.
func (mr *MocksessionStoreMockRecorder) CommitRefresh(ctx, params any) *MocksessionStoreCommitRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitRefresh", reflect.TypeOf((*MocksessionStore)(nil).CommitRefresh), ctx, params)
	return &MocksessionStoreCommitRefreshCall{Call: call}
}

// MocksessionStoreCommitRefreshCall wrap *gomock.Call
type MocksessionStoreCommitRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionStoreCommitRefreshCall) Return(arg0 error) *MocksessionStoreCommitRefreshCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionStoreCommitRefreshCall) Do(f func(context.Context, refreshCommitParams) error) *MocksessionStoreCommitRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionStoreCommitRefreshCall) DoAndReturn(f func(context.Context, refreshCommitParams) error) *MocksessionStoreCommitRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MocksessionStore) Create(ctx context.Context, key sessionKey, record storedRecord, expiresAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, key, record, expiresAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocksessionStoreMockRecorder) Create(ctx, key, record, expiresAt any) *MocksessionStoreCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocksessionStore)(nil).Create), ctx, key, record, expiresAt)
	return &MocksessionStoreCreateCall{Call: call}
}

// MocksessionStoreCreateCall wrap *gomock.Call
type MocksessionStoreCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionStoreCreateCall) Return(arg0 bool, arg1 error) *MocksessionStoreCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionStoreCreateCall) Do(f func(context.Context, sessionKey, storedRecord, time.Time) (bool, error)) *MocksessionStoreCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionStoreCreateCall) DoAndReturn(f func(context.Context, sessionKey, storedRecord, time.Time) (bool, error)) *MocksessionStoreCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GateRefresh mocks base method.
func (m *MocksessionStore) GateRefresh(ctx context.Context, params refreshGateParams) (refreshState, storedRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GateRefresh", ctx, params)
	ret0, _ := ret[0].(refreshState)
	ret1, _ := ret[1].(storedRecord)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GateRefresh indicates an expected call of GateRefresh.
func (mr *MocksessionStoreMockRecorder) GateRefresh(ctx, params any) *MocksessionStoreGateRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GateRefresh", reflect.TypeOf((*MocksessionStore)(nil).GateRefresh), ctx, params)
	return &MocksessionStoreGateRefreshCall{Call: call}
}

// MocksessionStoreGateRefreshCall wrap *gomock.Call
type MocksessionStoreGateRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionStoreGateRefreshCall) Return(arg0 refreshState, arg1 storedRecord, arg2 error) *MocksessionStoreGateRefreshCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionStoreGateRefreshCall) Do(f func(context.Context, refreshGateParams) (refreshState, storedRecord, error)) *MocksessionStoreGateRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionStoreGateRefreshCall) DoAndReturn(f func(context.Context, refreshGateParams) (refreshState, storedRecord, error)) *MocksessionStoreGateRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReleaseRefresh mocks base method.
func (m *MocksessionStore) ReleaseRefresh(ctx context.Context, key sessionKey, owner string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseRefresh", ctx, key, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseRefresh indicates an expected call of ReleaseRefresh.
func (mr *MocksessionStoreMockRecorder) ReleaseRefresh(ctx, key, owner any) *MocksessionStoreReleaseRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRefresh", reflect.TypeOf((*MocksessionStore)(nil).ReleaseRefresh), ctx, key, owner)
	return &MocksessionStoreReleaseRefreshCall{Call: call}
}

// MocksessionStoreReleaseRefreshCall wrap *gomock.Call
type MocksessionStoreReleaseRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionStoreReleaseRefreshCall) Return(arg0 error) *MocksessionStoreReleaseRefreshCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionStoreReleaseRefreshCall) Do(f func(context.Context, sessionKey, string) error) *MocksessionStoreReleaseRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionStoreReleaseRefreshCall) DoAndReturn(f func(context.Context, sessionKey, string) error) *MocksessionStoreReleaseRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MocksessionStore) Revoke(ctx context.Context, key sessionKey) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MocksessionStoreMockRecorder) Revoke(ctx, key any) *MocksessionStoreRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MocksessionStore)(nil).Revoke), ctx, key)
	return &MocksessionStoreRevokeCall{Call: call}
}

// MocksessionStoreRevokeCall wrap *gomock.Call
type MocksessionStoreRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionStoreRevokeCall) Return(arg0 string, arg1 error) *MocksessionStoreRevokeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionStoreRevokeCall) Do(f func(context.Context, sessionKey) (string, error)) *MocksessionStoreRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionStoreRevokeCall) DoAndReturn(f func(context.Context, sessionKey) (string, error)) *MocksessionStoreRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MocksessionStore) Status(ctx context.Context, key sessionKey) (storedRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, key)
	ret0, _ := ret[0].(storedRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MocksessionStoreMockRecorder) Status(ctx, key any) *MocksessionStoreStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MocksessionStore)(nil).Status), ctx, key)
	return &MocksessionStoreStatusCall{Call: call}
}

// MocksessionStoreStatusCall wrap *gomock.Call
type MocksessionStoreStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionStoreStatusCall) Return(arg0 storedRecord, arg1 error) *MocksessionStoreStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionStoreStatusCall) Do(f func(context.Context, sessionKey) (storedRecord, error)) *MocksessionStoreStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionStoreStatusCall) DoAndReturn(f func(context.Context, sessionKey) (storedRecord, error)) *MocksessionStoreStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
