# https://git-cliff.org/docs/configuration

[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | striptags | trim }}

{% for commit in commits -%}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endfor -%}

{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->New features" },
  { message = "^fix", group = "<!-- 1 -->Bug fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Refactoring" },
  { message = "^docs", group = "<!-- 4 -->Documentation" },
  { message = "^(build|ci|test|chore)", skip = true },
  { message = ".*", group = "<!-- 5 -->Other changes" },
]
sort_commits = "oldest"
topo_order = false
