// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/oidcsession (interfaces: SessionBackend,TokenService,Encryptor)
//
// Generated by this command:
//
//	mockgen -destination mocks/interfaces.gen.go -package mocks . SessionBackend,TokenService,Encryptor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	oidcsession "github.com/devctllabs/go-libs/oidcsession"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionBackend is a mock of SessionBackend interface.
type MockSessionBackend struct {
	ctrl     *gomock.Controller
	recorder *MockSessionBackendMockRecorder
	isgomock struct{}
}

// MockSessionBackendMockRecorder is the mock recorder for MockSessionBackend.
type MockSessionBackendMockRecorder struct {
	mock *MockSessionBackend
}

// NewMockSessionBackend creates a new mock instance.
func NewMockSessionBackend(ctrl *gomock.Controller) *MockSessionBackend {
	mock := &MockSessionBackend{ctrl: ctrl}
	mock.recorder = &MockSessionBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionBackend) EXPECT() *MockSessionBackendMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionBackend) Create(ctx context.Context, params oidcsession.CreateSessionParams) (oidcsession.CreateSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(oidcsession.CreateSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionBackendMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionBackend)(nil).Create), ctx, params)
}

// Refresh mocks base method.
func (m *MockSessionBackend) Refresh(ctx context.Context, credential oidcsession.SessionCredential) (oidcsession.RefreshSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, credential)
	ret0, _ := ret[0].(oidcsession.RefreshSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockSessionBackendMockRecorder) Refresh(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockSessionBackend)(nil).Refresh), ctx, credential)
}

// Revoke mocks base method.
func (m *MockSessionBackend) Revoke(ctx context.Context, credential oidcsession.SessionCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionBackendMockRecorder) Revoke(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionBackend)(nil).Revoke), ctx, credential)
}

// Status mocks base method.
func (m *MockSessionBackend) Status(ctx context.Context, credential oidcsession.SessionCredential) (oidcsession.SessionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, credential)
	ret0, _ := ret[0].(oidcsession.SessionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockSessionBackendMockRecorder) Status(ctx, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockSessionBackend)(nil).Status), ctx, credential)
}

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// Refresh mocks base method.
func (m *MockTokenService) Refresh(ctx context.Context, refreshToken string) (oidcsession.ProviderTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(oidcsession.ProviderTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockTokenServiceMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockTokenService)(nil).Refresh), ctx, refreshToken)
}

// Revoke mocks base method.
func (m *MockTokenService) Revoke(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenServiceMockRecorder) Revoke(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenService)(nil).Revoke), ctx, refreshToken)
}

// MockEncryptor is a mock of Encryptor interface.
type MockEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorMockRecorder
	isgomock struct{}
}

// MockEncryptorMockRecorder is the mock recorder for MockEncryptor.
type MockEncryptorMockRecorder struct {
	mock *MockEncryptor
}

// NewMockEncryptor creates a new mock instance.
func NewMockEncryptor(ctrl *gomock.Controller) *MockEncryptor {
	mock := &MockEncryptor{ctrl: ctrl}
	mock.recorder = &MockEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptor) EXPECT() *MockEncryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptor) Decrypt(ctx context.Context, ciphertext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, ciphertext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptorMockRecorder) Decrypt(ctx, ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptor)(nil).Decrypt), ctx, ciphertext)
}

// Encrypt mocks base method.
func (m *MockEncryptor) Encrypt(ctx context.Context, plaintext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, plaintext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptorMockRecorder) Encrypt(ctx, plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptor)(nil).Encrypt), ctx, plaintext)
}
