// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/txmanager (interfaces: Backend)
//
// Generated by this command:
//
//	mockgen -destination mocks/backend.gen.go -package mocks . Backend
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	txmanager "github.com/devctllabs/go-libs/txmanager"
	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder[T]
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder[T any] struct {
	mock *MockBackend[T]
}

// NewMockBackend creates a new mock instance.
func NewMockBackend[T any](ctrl *gomock.Controller) *MockBackend[T] {
	mock := &MockBackend[T]{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend[T]) EXPECT() *MockBackendMockRecorder[T] {
	return m.recorder
}

// Begin mocks base method.
func (m *MockBackend[T]) Begin(ctx context.Context, spec txmanager.BeginSpec) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, spec)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockBackendMockRecorder[T]) Begin(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockBackend[T])(nil).Begin), ctx, spec)
}

// Commit mocks base method.
func (m *MockBackend[T]) Commit(ctx context.Context, tx T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockBackendMockRecorder[T]) Commit(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockBackend[T])(nil).Commit), ctx, tx)
}

// Rollback mocks base method.
func (m *MockBackend[T]) Rollback(ctx context.Context, tx T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockBackendMockRecorder[T]) Rollback(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockBackend[T])(nil).Rollback), ctx, tx)
}
