// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/grpcserver (interfaces: PanicObserver)
//
// Generated by this command:
//
//	mockgen -destination mocks/panic_observer.gen.go -package mocks . PanicObserver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	grpcserver "github.com/devctllabs/go-libs/grpcserver"
	gomock "go.uber.org/mock/gomock"
)

// MockPanicObserver is a mock of PanicObserver interface.
type MockPanicObserver struct {
	ctrl     *gomock.Controller
	recorder *MockPanicObserverMockRecorder
	isgomock struct{}
}

// MockPanicObserverMockRecorder is the mock recorder for MockPanicObserver.
type MockPanicObserverMockRecorder struct {
	mock *MockPanicObserver
}

// NewMockPanicObserver creates a new mock instance.
func NewMockPanicObserver(ctrl *gomock.Controller) *MockPanicObserver {
	mock := &MockPanicObserver{ctrl: ctrl}
	mock.recorder = &MockPanicObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPanicObserver) EXPECT() *MockPanicObserverMockRecorder {
	return m.recorder
}

// ObservePanic mocks base method.
func (m *MockPanicObserver) ObservePanic(ctx context.Context, event grpcserver.PanicEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObservePanic", ctx, event)
}

// ObservePanic indicates an expected call of ObservePanic.
func (mr *MockPanicObserverMockRecorder) ObservePanic(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObservePanic", reflect.TypeOf((*MockPanicObserver)(nil).ObservePanic), ctx, event)
}
