// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/codexapp (interfaces: ServerRequestHandler)
//
// Generated by this command:
//
//	mockgen -destination mocks/server_requests.gen.go -package mocks . ServerRequestHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	codexapp "github.com/devctllabs/go-libs/codexapp"
	gomock "go.uber.org/mock/gomock"
)

// MockServerRequestHandler is a mock of ServerRequestHandler interface.
type MockServerRequestHandler struct {
	ctrl     *gomock.Controller
	recorder *MockServerRequestHandlerMockRecorder
	isgomock struct{}
}

// MockServerRequestHandlerMockRecorder is the mock recorder for MockServerRequestHandler.
type MockServerRequestHandlerMockRecorder struct {
	mock *MockServerRequestHandler
}

// NewMockServerRequestHandler creates a new mock instance.
func NewMockServerRequestHandler(ctrl *gomock.Controller) *MockServerRequestHandler {
	mock := &MockServerRequestHandler{ctrl: ctrl}
	mock.recorder = &MockServerRequestHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerRequestHandler) EXPECT() *MockServerRequestHandlerMockRecorder {
	return m.recorder
}

// HandleServerRequest mocks base method.
func (m *MockServerRequestHandler) HandleServerRequest(ctx context.Context, request codexapp.ServerRequest) (codexapp.ServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleServerRequest", ctx, request)
	ret0, _ := ret[0].(codexapp.ServerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleServerRequest indicates an expected call of HandleServerRequest.
func (mr *MockServerRequestHandlerMockRecorder) HandleServerRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleServerRequest", reflect.TypeOf((*MockServerRequestHandler)(nil).HandleServerRequest), ctx, request)
}
