// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/oidcsession (interfaces: SessionBackend,Encryptor)
//
// Generated by this command:
//
//	mockgen -destination=internal_dependencies.gen_test.go -package=oidcsession -typed -self_package=github.com/devctllabs/go-libs/oidcsession . SessionBackend,Encryptor
//

// Package oidcsession is a generated GoMock package.
package oidcsession

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionBackend is a mock of SessionBackend interface.
type MockSessionBackend struct {
	ctrl     *gomock.Controller
	recorder *MockSessionBackendMockRecorder
	isgomock struct{}
}

// MockSessionBackendMockRecorder is the mock recorder for MockSessionBackend.
type MockSessionBackendMockRecorder struct {
	mock *MockSessionBackend
}

// NewMockSessionBackend creates a new mock instance.
func NewMockSessionBackend(ctrl *gomock.Controller) *MockSessionBackend {
	mock := &MockSessionBackend{ctrl: ctrl}
	mock.recorder = &MockSessionBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionBackend) EXPECT() *MockSessionBackendMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionBackend) Create(ctx context.Context, params CreateSessionParams) (CreateSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(CreateSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionBackendMockRecorder) Create(ctx, params any) *MockSessionBackendCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionBackend)(nil).Create), ctx, params)
	return &MockSessionBackendCreateCall{Call: call}
}

// MockSessionBackendCreateCall wrap *gomock.Call
type MockSessionBackendCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionBackendCreateCall) Return(result CreateSessionResult, err error) *MockSessionBackendCreateCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionBackendCreateCall) Do(f func(context.Context, CreateSessionParams) (CreateSessionResult, error)) *MockSessionBackendCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionBackendCreateCall) DoAndReturn(f func(context.Context, CreateSessionParams) (CreateSessionResult, error)) *MockSessionBackendCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Refresh mocks base method.
func (m *MockSessionBackend) Refresh(ctx context.Context, credential SessionCredential) (RefreshSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, credential)
	ret0, _ := ret[0].(RefreshSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockSessionBackendMockRecorder) Refresh(ctx, credential any) *MockSessionBackendRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockSessionBackend)(nil).Refresh), ctx, credential)
	return &MockSessionBackendRefreshCall{Call: call}
}

// MockSessionBackendRefreshCall wrap *gomock.Call
type MockSessionBackendRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionBackendRefreshCall) Return(result RefreshSessionResult, err error) *MockSessionBackendRefreshCall {
	c.Call = c.Call.Return(result, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionBackendRefreshCall) Do(f func(context.Context, SessionCredential) (RefreshSessionResult, error)) *MockSessionBackendRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionBackendRefreshCall) DoAndReturn(f func(context.Context, SessionCredential) (RefreshSessionResult, error)) *MockSessionBackendRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MockSessionBackend) Revoke(ctx context.Context, credential SessionCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionBackendMockRecorder) Revoke(ctx, credential any) *MockSessionBackendRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionBackend)(nil).Revoke), ctx, credential)
	return &MockSessionBackendRevokeCall{Call: call}
}

// MockSessionBackendRevokeCall wrap *gomock.Call
type MockSessionBackendRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionBackendRevokeCall) Return(arg0 error) *MockSessionBackendRevokeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionBackendRevokeCall) Do(f func(context.Context, SessionCredential) error) *MockSessionBackendRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionBackendRevokeCall) DoAndReturn(f func(context.Context, SessionCredential) error) *MockSessionBackendRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockSessionBackend) Status(ctx context.Context, credential SessionCredential) (SessionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, credential)
	ret0, _ := ret[0].(SessionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockSessionBackendMockRecorder) Status(ctx, credential any) *MockSessionBackendStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockSessionBackend)(nil).Status), ctx, credential)
	return &MockSessionBackendStatusCall{Call: call}
}

// MockSessionBackendStatusCall wrap *gomock.Call
type MockSessionBackendStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionBackendStatusCall) Return(status SessionStatus, err error) *MockSessionBackendStatusCall {
	c.Call = c.Call.Return(status, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionBackendStatusCall) Do(f func(context.Context, SessionCredential) (SessionStatus, error)) *MockSessionBackendStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionBackendStatusCall) DoAndReturn(f func(context.Context, SessionCredential) (SessionStatus, error)) *MockSessionBackendStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEncryptor is a mock of Encryptor interface.
type MockEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorMockRecorder
	isgomock struct{}
}

// MockEncryptorMockRecorder is the mock recorder for MockEncryptor.
type MockEncryptorMockRecorder struct {
	mock *MockEncryptor
}

// NewMockEncryptor creates a new mock instance.
func NewMockEncryptor(ctrl *gomock.Controller) *MockEncryptor {
	mock := &MockEncryptor{ctrl: ctrl}
	mock.recorder = &MockEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptor) EXPECT() *MockEncryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptor) Decrypt(ctx context.Context, ciphertext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, ciphertext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptorMockRecorder) Decrypt(ctx, ciphertext any) *MockEncryptorDecryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptor)(nil).Decrypt), ctx, ciphertext)
	return &MockEncryptorDecryptCall{Call: call}
}

// MockEncryptorDecryptCall wrap *gomock.Call
type MockEncryptorDecryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncryptorDecryptCall) Return(plaintext []byte, err error) *MockEncryptorDecryptCall {
	c.Call = c.Call.Return(plaintext, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncryptorDecryptCall) Do(f func(context.Context, []byte) ([]byte, error)) *MockEncryptorDecryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncryptorDecryptCall) DoAndReturn(f func(context.Context, []byte) ([]byte, error)) *MockEncryptorDecryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Encrypt mocks base method.
func (m *MockEncryptor) Encrypt(ctx context.Context, plaintext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, plaintext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptorMockRecorder) Encrypt(ctx, plaintext any) *MockEncryptorEncryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptor)(nil).Encrypt), ctx, plaintext)
	return &MockEncryptorEncryptCall{Call: call}
}

// MockEncryptorEncryptCall wrap *gomock.Call
type MockEncryptorEncryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncryptorEncryptCall) Return(ciphertext []byte, err error) *MockEncryptorEncryptCall {
	c.Call = c.Call.Return(ciphertext, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncryptorEncryptCall) Do(f func(context.Context, []byte) ([]byte, error)) *MockEncryptorEncryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncryptorEncryptCall) DoAndReturn(f func(context.Context, []byte) ([]byte, error)) *MockEncryptorEncryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
