// Code generated by MockGen. DO NOT EDIT.
// Source: internal_contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal_contracts.go -destination=internal_contracts.gen_test.go -package=oidcsession -typed
//

// Package oidcsession is a generated GoMock package.
package oidcsession

import (
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocksessionApplication is a mock of sessionApplication interface.
type MocksessionApplication struct {
	ctrl     *gomock.Controller
	recorder *MocksessionApplicationMockRecorder
	isgomock struct{}
}

// MocksessionApplicationMockRecorder is the mock recorder for MocksessionApplication.
type MocksessionApplicationMockRecorder struct {
	mock *MocksessionApplication
}

// NewMocksessionApplication creates a new mock instance.
func NewMocksessionApplication(ctrl *gomock.Controller) *MocksessionApplication {
	mock := &MocksessionApplication{ctrl: ctrl}
	mock.recorder = &MocksessionApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionApplication) EXPECT() *MocksessionApplicationMockRecorder {
	return m.recorder
}

// BeginLogin mocks base method.
func (m *MocksessionApplication) BeginLogin(ctx context.Context, command beginLoginCommand) (beginLoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginLogin", ctx, command)
	ret0, _ := ret[0].(beginLoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginLogin indicates an expected call of BeginLogin.
func (mr *MocksessionApplicationMockRecorder) BeginLogin(ctx, command any) *MocksessionApplicationBeginLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginLogin", reflect.TypeOf((*MocksessionApplication)(nil).BeginLogin), ctx, command)
	return &MocksessionApplicationBeginLoginCall{Call: call}
}

// MocksessionApplicationBeginLoginCall wrap *gomock.Call
type MocksessionApplicationBeginLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionApplicationBeginLoginCall) Return(arg0 beginLoginResult, arg1 error) *MocksessionApplicationBeginLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionApplicationBeginLoginCall) Do(f func(context.Context, beginLoginCommand) (beginLoginResult, error)) *MocksessionApplicationBeginLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionApplicationBeginLoginCall) DoAndReturn(f func(context.Context, beginLoginCommand) (beginLoginResult, error)) *MocksessionApplicationBeginLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CompleteLogin mocks base method.
func (m *MocksessionApplication) CompleteLogin(ctx context.Context, command completeLoginCommand) (completeLoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteLogin", ctx, command)
	ret0, _ := ret[0].(completeLoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteLogin indicates an expected call of CompleteLogin.
func (mr *MocksessionApplicationMockRecorder) CompleteLogin(ctx, command any) *MocksessionApplicationCompleteLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteLogin", reflect.TypeOf((*MocksessionApplication)(nil).CompleteLogin), ctx, command)
	return &MocksessionApplicationCompleteLoginCall{Call: call}
}

// MocksessionApplicationCompleteLoginCall wrap *gomock.Call
type MocksessionApplicationCompleteLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionApplicationCompleteLoginCall) Return(arg0 completeLoginResult, arg1 error) *MocksessionApplicationCompleteLoginCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionApplicationCompleteLoginCall) Do(f func(context.Context, completeLoginCommand) (completeLoginResult, error)) *MocksessionApplicationCompleteLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionApplicationCompleteLoginCall) DoAndReturn(f func(context.Context, completeLoginCommand) (completeLoginResult, error)) *MocksessionApplicationCompleteLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MocksessionApplication) Logout(ctx context.Context, credential SessionCredential) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Logout", ctx, credential)
}

// Logout indicates an expected call of Logout.
func (mr *MocksessionApplicationMockRecorder) Logout(ctx, credential any) *MocksessionApplicationLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MocksessionApplication)(nil).Logout), ctx, credential)
	return &MocksessionApplicationLogoutCall{Call: call}
}

// MocksessionApplicationLogoutCall wrap *gomock.Call
type MocksessionApplicationLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionApplicationLogoutCall) Return() *MocksessionApplicationLogoutCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionApplicationLogoutCall) Do(f func(context.Context, SessionCredential)) *MocksessionApplicationLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionApplicationLogoutCall) DoAndReturn(f func(context.Context, SessionCredential)) *MocksessionApplicationLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Refresh mocks base method.
func (m *MocksessionApplication) Refresh(ctx context.Context, credential SessionCredential) (RefreshSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, credential)
	ret0, _ := ret[0].(RefreshSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MocksessionApplicationMockRecorder) Refresh(ctx, credential any) *MocksessionApplicationRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MocksessionApplication)(nil).Refresh), ctx, credential)
	return &MocksessionApplicationRefreshCall{Call: call}
}

// MocksessionApplicationRefreshCall wrap *gomock.Call
type MocksessionApplicationRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionApplicationRefreshCall) Return(arg0 RefreshSessionResult, arg1 error) *MocksessionApplicationRefreshCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionApplicationRefreshCall) Do(f func(context.Context, SessionCredential) (RefreshSessionResult, error)) *MocksessionApplicationRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionApplicationRefreshCall) DoAndReturn(f func(context.Context, SessionCredential) (RefreshSessionResult, error)) *MocksessionApplicationRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Session mocks base method.
func (m *MocksessionApplication) Session(ctx context.Context, credential SessionCredential) (SessionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, credential)
	ret0, _ := ret[0].(SessionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MocksessionApplicationMockRecorder) Session(ctx, credential any) *MocksessionApplicationSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MocksessionApplication)(nil).Session), ctx, credential)
	return &MocksessionApplicationSessionCall{Call: call}
}

// MocksessionApplicationSessionCall wrap *gomock.Call
type MocksessionApplicationSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksessionApplicationSessionCall) Return(arg0 SessionStatus, arg1 error) *MocksessionApplicationSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksessionApplicationSessionCall) Do(f func(context.Context, SessionCredential) (SessionStatus, error)) *MocksessionApplicationSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksessionApplicationSessionCall) DoAndReturn(f func(context.Context, SessionCredential) (SessionStatus, error)) *MocksessionApplicationSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockloginProvider is a mock of loginProvider interface.
type MockloginProvider struct {
	ctrl     *gomock.Controller
	recorder *MockloginProviderMockRecorder
	isgomock struct{}
}

// MockloginProviderMockRecorder is the mock recorder for MockloginProvider.
type MockloginProviderMockRecorder struct {
	mock *MockloginProvider
}

// NewMockloginProvider creates a new mock instance.
func NewMockloginProvider(ctrl *gomock.Controller) *MockloginProvider {
	mock := &MockloginProvider{ctrl: ctrl}
	mock.recorder = &MockloginProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockloginProvider) EXPECT() *MockloginProviderMockRecorder {
	return m.recorder
}

// authorizationURL mocks base method.
func (m *MockloginProvider) authorizationURL(state, nonce, verifier string, parameters url.Values) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "authorizationURL", state, nonce, verifier, parameters)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// authorizationURL indicates an expected call of authorizationURL.
func (mr *MockloginProviderMockRecorder) authorizationURL(state, nonce, verifier, parameters any) *MockloginProviderauthorizationURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "authorizationURL", reflect.TypeOf((*MockloginProvider)(nil).authorizationURL), state, nonce, verifier, parameters)
	return &MockloginProviderauthorizationURLCall{Call: call}
}

// MockloginProviderauthorizationURLCall wrap *gomock.Call
type MockloginProviderauthorizationURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockloginProviderauthorizationURLCall) Return(arg0 string, arg1 error) *MockloginProviderauthorizationURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockloginProviderauthorizationURLCall) Do(f func(string, string, string, url.Values) (string, error)) *MockloginProviderauthorizationURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockloginProviderauthorizationURLCall) DoAndReturn(f func(string, string, string, url.Values) (string, error)) *MockloginProviderauthorizationURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// exchange mocks base method.
func (m *MockloginProvider) exchange(ctx context.Context, code, nonce, verifier, methodID string) (ProviderTokens, VerifiedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "exchange", ctx, code, nonce, verifier, methodID)
	ret0, _ := ret[0].(ProviderTokens)
	ret1, _ := ret[1].(VerifiedIdentity)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// exchange indicates an expected call of exchange.
func (mr *MockloginProviderMockRecorder) exchange(ctx, code, nonce, verifier, methodID any) *MockloginProviderexchangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "exchange", reflect.TypeOf((*MockloginProvider)(nil).exchange), ctx, code, nonce, verifier, methodID)
	return &MockloginProviderexchangeCall{Call: call}
}

// MockloginProviderexchangeCall wrap *gomock.Call
type MockloginProviderexchangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockloginProviderexchangeCall) Return(arg0 ProviderTokens, arg1 VerifiedIdentity, arg2 error) *MockloginProviderexchangeCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockloginProviderexchangeCall) Do(f func(context.Context, string, string, string, string) (ProviderTokens, VerifiedIdentity, error)) *MockloginProviderexchangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockloginProviderexchangeCall) DoAndReturn(f func(context.Context, string, string, string, string) (ProviderTokens, VerifiedIdentity, error)) *MockloginProviderexchangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
