// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/kafkaoutbox (interfaces: Appender,BatchPublisher,Observer)
//
// Generated by this command:
//
//	mockgen -destination=contracts.gen_test.go -package=kafkaoutbox -typed . Appender,BatchPublisher,Observer
//

// Package kafkaoutbox is a generated GoMock package.
package kafkaoutbox

import (
	context "context"
	reflect "reflect"

	kafka "github.com/devctllabs/go-libs/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockAppender is a mock of Appender interface.
type MockAppender struct {
	ctrl     *gomock.Controller
	recorder *MockAppenderMockRecorder
	isgomock struct{}
}

// MockAppenderMockRecorder is the mock recorder for MockAppender.
type MockAppenderMockRecorder struct {
	mock *MockAppender
}

// NewMockAppender creates a new mock instance.
func NewMockAppender(ctrl *gomock.Controller) *MockAppender {
	mock := &MockAppender{ctrl: ctrl}
	mock.recorder = &MockAppenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppender) EXPECT() *MockAppenderMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockAppender) Append(ctx context.Context, event Event[[]byte]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockAppenderMockRecorder) Append(ctx, event any) *MockAppenderAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockAppender)(nil).Append), ctx, event)
	return &MockAppenderAppendCall{Call: call}
}

// MockAppenderAppendCall wrap *gomock.Call
type MockAppenderAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppenderAppendCall) Return(arg0 error) *MockAppenderAppendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppenderAppendCall) Do(f func(context.Context, Event[[]byte]) error) *MockAppenderAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppenderAppendCall) DoAndReturn(f func(context.Context, Event[[]byte]) error) *MockAppenderAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBatchPublisher is a mock of BatchPublisher interface.
type MockBatchPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockBatchPublisherMockRecorder
	isgomock struct{}
}

// MockBatchPublisherMockRecorder is the mock recorder for MockBatchPublisher.
type MockBatchPublisherMockRecorder struct {
	mock *MockBatchPublisher
}

// NewMockBatchPublisher creates a new mock instance.
func NewMockBatchPublisher(ctrl *gomock.Controller) *MockBatchPublisher {
	mock := &MockBatchPublisher{ctrl: ctrl}
	mock.recorder = &MockBatchPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchPublisher) EXPECT() *MockBatchPublisherMockRecorder {
	return m.recorder
}

// SendBatch mocks base method.
func (m *MockBatchPublisher) SendBatch(ctx context.Context, messages []kafka.OutgoingMessage[[]byte]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockBatchPublisherMockRecorder) SendBatch(ctx, messages any) *MockBatchPublisherSendBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockBatchPublisher)(nil).SendBatch), ctx, messages)
	return &MockBatchPublisherSendBatchCall{Call: call}
}

// MockBatchPublisherSendBatchCall wrap *gomock.Call
type MockBatchPublisherSendBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatchPublisherSendBatchCall) Return(arg0 error) *MockBatchPublisherSendBatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatchPublisherSendBatchCall) Do(f func(context.Context, []kafka.OutgoingMessage[[]byte]) error) *MockBatchPublisherSendBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatchPublisherSendBatchCall) DoAndReturn(f func(context.Context, []kafka.OutgoingMessage[[]byte]) error) *MockBatchPublisherSendBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// BatchCompleted mocks base method.
func (m *MockObserver) BatchCompleted(ctx context.Context, result BatchResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BatchCompleted", ctx, result)
}

// BatchCompleted indicates an expected call of BatchCompleted.
func (mr *MockObserverMockRecorder) BatchCompleted(ctx, result any) *MockObserverBatchCompletedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCompleted", reflect.TypeOf((*MockObserver)(nil).BatchCompleted), ctx, result)
	return &MockObserverBatchCompletedCall{Call: call}
}

// MockObserverBatchCompletedCall wrap *gomock.Call
type MockObserverBatchCompletedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObserverBatchCompletedCall) Return() *MockObserverBatchCompletedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObserverBatchCompletedCall) Do(f func(context.Context, BatchResult)) *MockObserverBatchCompletedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObserverBatchCompletedCall) DoAndReturn(f func(context.Context, BatchResult)) *MockObserverBatchCompletedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enqueued mocks base method.
func (m *MockObserver) Enqueued(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enqueued", ctx)
}

// Enqueued indicates an expected call of Enqueued.
func (mr *MockObserverMockRecorder) Enqueued(ctx any) *MockObserverEnqueuedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueued", reflect.TypeOf((*MockObserver)(nil).Enqueued), ctx)
	return &MockObserverEnqueuedCall{Call: call}
}

// MockObserverEnqueuedCall wrap *gomock.Call
type MockObserverEnqueuedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObserverEnqueuedCall) Return() *MockObserverEnqueuedCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObserverEnqueuedCall) Do(f func(context.Context)) *MockObserverEnqueuedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObserverEnqueuedCall) DoAndReturn(f func(context.Context)) *MockObserverEnqueuedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FencingConflict mocks base method.
func (m *MockObserver) FencingConflict(ctx context.Context, event FencingEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FencingConflict", ctx, event)
}

// FencingConflict indicates an expected call of FencingConflict.
func (mr *MockObserverMockRecorder) FencingConflict(ctx, event any) *MockObserverFencingConflictCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FencingConflict", reflect.TypeOf((*MockObserver)(nil).FencingConflict), ctx, event)
	return &MockObserverFencingConflictCall{Call: call}
}

// MockObserverFencingConflictCall wrap *gomock.Call
type MockObserverFencingConflictCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObserverFencingConflictCall) Return() *MockObserverFencingConflictCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObserverFencingConflictCall) Do(f func(context.Context, FencingEvent)) *MockObserverFencingConflictCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObserverFencingConflictCall) DoAndReturn(f func(context.Context, FencingEvent)) *MockObserverFencingConflictCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Retry mocks base method.
func (m *MockObserver) Retry(ctx context.Context, event RetryEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Retry", ctx, event)
}

// Retry indicates an expected call of Retry.
func (mr *MockObserverMockRecorder) Retry(ctx, event any) *MockObserverRetryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockObserver)(nil).Retry), ctx, event)
	return &MockObserverRetryCall{Call: call}
}

// MockObserverRetryCall wrap *gomock.Call
type MockObserverRetryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObserverRetryCall) Return() *MockObserverRetryCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObserverRetryCall) Do(f func(context.Context, RetryEvent)) *MockObserverRetryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObserverRetryCall) DoAndReturn(f func(context.Context, RetryEvent)) *MockObserverRetryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartOperation mocks base method.
func (m *MockObserver) StartOperation(ctx context.Context, operation Operation) (context.Context, OperationDone) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartOperation", ctx, operation)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(OperationDone)
	return ret0, ret1
}

// StartOperation indicates an expected call of StartOperation.
func (mr *MockObserverMockRecorder) StartOperation(ctx, operation any) *MockObserverStartOperationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartOperation", reflect.TypeOf((*MockObserver)(nil).StartOperation), ctx, operation)
	return &MockObserverStartOperationCall{Call: call}
}

// MockObserverStartOperationCall wrap *gomock.Call
type MockObserverStartOperationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObserverStartOperationCall) Return(arg0 context.Context, arg1 OperationDone) *MockObserverStartOperationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObserverStartOperationCall) Do(f func(context.Context, Operation) (context.Context, OperationDone)) *MockObserverStartOperationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObserverStartOperationCall) DoAndReturn(f func(context.Context, Operation) (context.Context, OperationDone)) *MockObserverStartOperationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TopologyReconciled mocks base method.
func (m *MockObserver) TopologyReconciled(ctx context.Context, result TopologyResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TopologyReconciled", ctx, result)
}

// TopologyReconciled indicates an expected call of TopologyReconciled.
func (mr *MockObserverMockRecorder) TopologyReconciled(ctx, result any) *MockObserverTopologyReconciledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopologyReconciled", reflect.TypeOf((*MockObserver)(nil).TopologyReconciled), ctx, result)
	return &MockObserverTopologyReconciledCall{Call: call}
}

// MockObserverTopologyReconciledCall wrap *gomock.Call
type MockObserverTopologyReconciledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockObserverTopologyReconciledCall) Return() *MockObserverTopologyReconciledCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockObserverTopologyReconciledCall) Do(f func(context.Context, TopologyResult)) *MockObserverTopologyReconciledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockObserverTopologyReconciledCall) DoAndReturn(f func(context.Context, TopologyResult)) *MockObserverTopologyReconciledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
