// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/kafka (interfaces: Encoder)
//
// Generated by this command:
//
//	mockgen -destination=encoder.gen_test.go -package=kafkaoutbox -typed github.com/devctllabs/go-libs/kafka Encoder
//

// Package kafkaoutbox is a generated GoMock package.
package kafkaoutbox

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncoder is a mock of Encoder interface.
type MockEncoder[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder[T]
	isgomock struct{}
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder[T any] struct {
	mock *MockEncoder[T]
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder[T any](ctrl *gomock.Controller) *MockEncoder[T] {
	mock := &MockEncoder[T]{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder[T]) EXPECT() *MockEncoderMockRecorder[T] {
	return m.recorder
}

// Encode mocks base method.
func (m *MockEncoder[T]) Encode(ctx context.Context, value T) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", ctx, value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockEncoderMockRecorder[T]) Encode(ctx, value any) *MockEncoderEncodeCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockEncoder[T])(nil).Encode), ctx, value)
	return &MockEncoderEncodeCall[T]{Call: call}
}

// MockEncoderEncodeCall wrap *gomock.Call
type MockEncoderEncodeCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncoderEncodeCall[T]) Return(arg0 []byte, arg1 error) *MockEncoderEncodeCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncoderEncodeCall[T]) Do(f func(context.Context, T) ([]byte, error)) *MockEncoderEncodeCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncoderEncodeCall[T]) DoAndReturn(f func(context.Context, T) ([]byte, error)) *MockEncoderEncodeCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
