// Code generated by MockGen. DO NOT EDIT.
// Source: consumer_client.go
//
// Generated by this command:
//
//	mockgen -source=consumer_client.go -destination=consumer_client.gen_test.go -package=kafka -typed
//

// Package kafka is a generated GoMock package.
package kafka

import (
	context "context"
	reflect "reflect"

	kgo "github.com/twmb/franz-go/pkg/kgo"
	gomock "go.uber.org/mock/gomock"
)

// MockconsumerClient is a mock of consumerClient interface.
type MockconsumerClient struct {
	ctrl     *gomock.Controller
	recorder *MockconsumerClientMockRecorder
	isgomock struct{}
}

// MockconsumerClientMockRecorder is the mock recorder for MockconsumerClient.
type MockconsumerClientMockRecorder struct {
	mock *MockconsumerClient
}

// NewMockconsumerClient creates a new mock instance.
func NewMockconsumerClient(ctrl *gomock.Controller) *MockconsumerClient {
	mock := &MockconsumerClient{ctrl: ctrl}
	mock.recorder = &MockconsumerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconsumerClient) EXPECT() *MockconsumerClientMockRecorder {
	return m.recorder
}

// AllowRebalance mocks base method.
func (m *MockconsumerClient) AllowRebalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AllowRebalance")
}

// AllowRebalance indicates an expected call of AllowRebalance.
func (mr *MockconsumerClientMockRecorder) AllowRebalance() *MockconsumerClientAllowRebalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowRebalance", reflect.TypeOf((*MockconsumerClient)(nil).AllowRebalance))
	return &MockconsumerClientAllowRebalanceCall{Call: call}
}

// MockconsumerClientAllowRebalanceCall wrap *gomock.Call
type MockconsumerClientAllowRebalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconsumerClientAllowRebalanceCall) Return() *MockconsumerClientAllowRebalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockconsumerClientAllowRebalanceCall) Do(f func()) *MockconsumerClientAllowRebalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconsumerClientAllowRebalanceCall) DoAndReturn(f func()) *MockconsumerClientAllowRebalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockconsumerClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockconsumerClientMockRecorder) Close() *MockconsumerClientCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockconsumerClient)(nil).Close))
	return &MockconsumerClientCloseCall{Call: call}
}

// MockconsumerClientCloseCall wrap *gomock.Call
type MockconsumerClientCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconsumerClientCloseCall) Return() *MockconsumerClientCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockconsumerClientCloseCall) Do(f func()) *MockconsumerClientCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconsumerClientCloseCall) DoAndReturn(f func()) *MockconsumerClientCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitRecords mocks base method.
func (m *MockconsumerClient) CommitRecords(ctx context.Context, records ...*kgo.Record) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range records {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitRecords", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitRecords indicates an expected call of CommitRecords.
func (mr *MockconsumerClientMockRecorder) CommitRecords(ctx any, records ...any) *MockconsumerClientCommitRecordsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, records...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitRecords", reflect.TypeOf((*MockconsumerClient)(nil).CommitRecords), varargs...)
	return &MockconsumerClientCommitRecordsCall{Call: call}
}

// MockconsumerClientCommitRecordsCall wrap *gomock.Call
type MockconsumerClientCommitRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconsumerClientCommitRecordsCall) Return(arg0 error) *MockconsumerClientCommitRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockconsumerClientCommitRecordsCall) Do(f func(context.Context, ...*kgo.Record) error) *MockconsumerClientCommitRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconsumerClientCommitRecordsCall) DoAndReturn(f func(context.Context, ...*kgo.Record) error) *MockconsumerClientCommitRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PollRecords mocks base method.
func (m *MockconsumerClient) PollRecords(ctx context.Context, maxRecords int) kgo.Fetches {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollRecords", ctx, maxRecords)
	ret0, _ := ret[0].(kgo.Fetches)
	return ret0
}

// PollRecords indicates an expected call of PollRecords.
func (mr *MockconsumerClientMockRecorder) PollRecords(ctx, maxRecords any) *MockconsumerClientPollRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollRecords", reflect.TypeOf((*MockconsumerClient)(nil).PollRecords), ctx, maxRecords)
	return &MockconsumerClientPollRecordsCall{Call: call}
}

// MockconsumerClientPollRecordsCall wrap *gomock.Call
type MockconsumerClientPollRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconsumerClientPollRecordsCall) Return(arg0 kgo.Fetches) *MockconsumerClientPollRecordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockconsumerClientPollRecordsCall) Do(f func(context.Context, int) kgo.Fetches) *MockconsumerClientPollRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconsumerClientPollRecordsCall) DoAndReturn(f func(context.Context, int) kgo.Fetches) *MockconsumerClientPollRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProduceSync mocks base method.
func (m *MockconsumerClient) ProduceSync(ctx context.Context, records ...*kgo.Record) kgo.ProduceResults {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range records {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProduceSync", varargs...)
	ret0, _ := ret[0].(kgo.ProduceResults)
	return ret0
}

// ProduceSync indicates an expected call of ProduceSync.
func (mr *MockconsumerClientMockRecorder) ProduceSync(ctx any, records ...any) *MockconsumerClientProduceSyncCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, records...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceSync", reflect.TypeOf((*MockconsumerClient)(nil).ProduceSync), varargs...)
	return &MockconsumerClientProduceSyncCall{Call: call}
}

// MockconsumerClientProduceSyncCall wrap *gomock.Call
type MockconsumerClientProduceSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconsumerClientProduceSyncCall) Return(arg0 kgo.ProduceResults) *MockconsumerClientProduceSyncCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockconsumerClientProduceSyncCall) Do(f func(context.Context, ...*kgo.Record) kgo.ProduceResults) *MockconsumerClientProduceSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconsumerClientProduceSyncCall) DoAndReturn(f func(context.Context, ...*kgo.Record) kgo.ProduceResults) *MockconsumerClientProduceSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
