// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/kafka (interfaces: Decoder,Encoder,BatchHandler)
//
// Generated by this command:
//
//	mockgen -destination=contracts.gen_test.go -package=kafka -typed . Decoder,Encoder,BatchHandler
//

// Package kafka is a generated GoMock package.
package kafka

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDecoder is a mock of Decoder interface.
type MockDecoder[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDecoderMockRecorder[T]
	isgomock struct{}
}

// MockDecoderMockRecorder is the mock recorder for MockDecoder.
type MockDecoderMockRecorder[T any] struct {
	mock *MockDecoder[T]
}

// NewMockDecoder creates a new mock instance.
func NewMockDecoder[T any](ctrl *gomock.Controller) *MockDecoder[T] {
	mock := &MockDecoder[T]{ctrl: ctrl}
	mock.recorder = &MockDecoderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoder[T]) EXPECT() *MockDecoderMockRecorder[T] {
	return m.recorder
}

// Decode mocks base method.
func (m *MockDecoder[T]) Decode(ctx context.Context, value []byte) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", ctx, value)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockDecoderMockRecorder[T]) Decode(ctx, value any) *MockDecoderDecodeCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockDecoder[T])(nil).Decode), ctx, value)
	return &MockDecoderDecodeCall[T]{Call: call}
}

// MockDecoderDecodeCall wrap *gomock.Call
type MockDecoderDecodeCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDecoderDecodeCall[T]) Return(arg0 T, arg1 error) *MockDecoderDecodeCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDecoderDecodeCall[T]) Do(f func(context.Context, []byte) (T, error)) *MockDecoderDecodeCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDecoderDecodeCall[T]) DoAndReturn(f func(context.Context, []byte) (T, error)) *MockDecoderDecodeCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEncoder is a mock of Encoder interface.
type MockEncoder[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder[T]
	isgomock struct{}
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder[T any] struct {
	mock *MockEncoder[T]
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder[T any](ctrl *gomock.Controller) *MockEncoder[T] {
	mock := &MockEncoder[T]{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder[T]) EXPECT() *MockEncoderMockRecorder[T] {
	return m.recorder
}

// Encode mocks base method.
func (m *MockEncoder[T]) Encode(ctx context.Context, value T) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", ctx, value)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockEncoderMockRecorder[T]) Encode(ctx, value any) *MockEncoderEncodeCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockEncoder[T])(nil).Encode), ctx, value)
	return &MockEncoderEncodeCall[T]{Call: call}
}

// MockEncoderEncodeCall wrap *gomock.Call
type MockEncoderEncodeCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncoderEncodeCall[T]) Return(arg0 []byte, arg1 error) *MockEncoderEncodeCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncoderEncodeCall[T]) Do(f func(context.Context, T) ([]byte, error)) *MockEncoderEncodeCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncoderEncodeCall[T]) DoAndReturn(f func(context.Context, T) ([]byte, error)) *MockEncoderEncodeCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBatchHandler is a mock of BatchHandler interface.
type MockBatchHandler[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockBatchHandlerMockRecorder[T]
	isgomock struct{}
}

// MockBatchHandlerMockRecorder is the mock recorder for MockBatchHandler.
type MockBatchHandlerMockRecorder[T any] struct {
	mock *MockBatchHandler[T]
}

// NewMockBatchHandler creates a new mock instance.
func NewMockBatchHandler[T any](ctrl *gomock.Controller) *MockBatchHandler[T] {
	mock := &MockBatchHandler[T]{ctrl: ctrl}
	mock.recorder = &MockBatchHandlerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchHandler[T]) EXPECT() *MockBatchHandlerMockRecorder[T] {
	return m.recorder
}

// Handle mocks base method.
func (m *MockBatchHandler[T]) Handle(ctx context.Context, batch *Batch[T]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, batch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockBatchHandlerMockRecorder[T]) Handle(ctx, batch any) *MockBatchHandlerHandleCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockBatchHandler[T])(nil).Handle), ctx, batch)
	return &MockBatchHandlerHandleCall[T]{Call: call}
}

// MockBatchHandlerHandleCall wrap *gomock.Call
type MockBatchHandlerHandleCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatchHandlerHandleCall[T]) Return(arg0 error) *MockBatchHandlerHandleCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatchHandlerHandleCall[T]) Do(f func(context.Context, *Batch[T]) error) *MockBatchHandlerHandleCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatchHandlerHandleCall[T]) DoAndReturn(f func(context.Context, *Batch[T]) error) *MockBatchHandlerHandleCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
