// Code generated by MockGen. DO NOT EDIT.
// Source: producer_client.go
//
// Generated by this command:
//
//	mockgen -source=producer_client.go -destination=producer_client.gen_test.go -package=kafka -typed
//

// Package kafka is a generated GoMock package.
package kafka

import (
	context "context"
	reflect "reflect"

	kgo "github.com/twmb/franz-go/pkg/kgo"
	gomock "go.uber.org/mock/gomock"
)

// MockrecordProducer is a mock of recordProducer interface.
type MockrecordProducer struct {
	ctrl     *gomock.Controller
	recorder *MockrecordProducerMockRecorder
	isgomock struct{}
}

// MockrecordProducerMockRecorder is the mock recorder for MockrecordProducer.
type MockrecordProducerMockRecorder struct {
	mock *MockrecordProducer
}

// NewMockrecordProducer creates a new mock instance.
func NewMockrecordProducer(ctrl *gomock.Controller) *MockrecordProducer {
	mock := &MockrecordProducer{ctrl: ctrl}
	mock.recorder = &MockrecordProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrecordProducer) EXPECT() *MockrecordProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockrecordProducer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockrecordProducerMockRecorder) Close() *MockrecordProducerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockrecordProducer)(nil).Close))
	return &MockrecordProducerCloseCall{Call: call}
}

// MockrecordProducerCloseCall wrap *gomock.Call
type MockrecordProducerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordProducerCloseCall) Return() *MockrecordProducerCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordProducerCloseCall) Do(f func()) *MockrecordProducerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordProducerCloseCall) DoAndReturn(f func()) *MockrecordProducerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProduceSync mocks base method.
func (m *MockrecordProducer) ProduceSync(ctx context.Context, records ...*kgo.Record) kgo.ProduceResults {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range records {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProduceSync", varargs...)
	ret0, _ := ret[0].(kgo.ProduceResults)
	return ret0
}

// ProduceSync indicates an expected call of ProduceSync.
func (mr *MockrecordProducerMockRecorder) ProduceSync(ctx any, records ...any) *MockrecordProducerProduceSyncCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, records...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceSync", reflect.TypeOf((*MockrecordProducer)(nil).ProduceSync), varargs...)
	return &MockrecordProducerProduceSyncCall{Call: call}
}

// MockrecordProducerProduceSyncCall wrap *gomock.Call
type MockrecordProducerProduceSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockrecordProducerProduceSyncCall) Return(arg0 kgo.ProduceResults) *MockrecordProducerProduceSyncCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockrecordProducerProduceSyncCall) Do(f func(context.Context, ...*kgo.Record) kgo.ProduceResults) *MockrecordProducerProduceSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockrecordProducerProduceSyncCall) DoAndReturn(f func(context.Context, ...*kgo.Record) kgo.ProduceResults) *MockrecordProducerProduceSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
