// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/go-libs/filesystem (interfaces: Copier,Merger,Writer,Remover)
//
// Generated by this command:
//
//	mockgen -destination mocks/filesystem.gen.go -package mocks . Copier,Merger,Writer,Remover
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCopier is a mock of Copier interface.
type MockCopier struct {
	ctrl     *gomock.Controller
	recorder *MockCopierMockRecorder
	isgomock struct{}
}

// MockCopierMockRecorder is the mock recorder for MockCopier.
type MockCopierMockRecorder struct {
	mock *MockCopier
}

// NewMockCopier creates a new mock instance.
func NewMockCopier(ctrl *gomock.Controller) *MockCopier {
	mock := &MockCopier{ctrl: ctrl}
	mock.recorder = &MockCopierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCopier) EXPECT() *MockCopierMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockCopier) Copy(ctx context.Context, source fs.FS, destination string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, source, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockCopierMockRecorder) Copy(ctx, source, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockCopier)(nil).Copy), ctx, source, destination)
}

// MockMerger is a mock of Merger interface.
type MockMerger struct {
	ctrl     *gomock.Controller
	recorder *MockMergerMockRecorder
	isgomock struct{}
}

// MockMergerMockRecorder is the mock recorder for MockMerger.
type MockMergerMockRecorder struct {
	mock *MockMerger
}

// NewMockMerger creates a new mock instance.
func NewMockMerger(ctrl *gomock.Controller) *MockMerger {
	mock := &MockMerger{ctrl: ctrl}
	mock.recorder = &MockMergerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerger) EXPECT() *MockMergerMockRecorder {
	return m.recorder
}

// Merge mocks base method.
func (m *MockMerger) Merge(ctx context.Context, source fs.FS, destination string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, source, destination)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockMergerMockRecorder) Merge(ctx, source, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockMerger)(nil).Merge), ctx, source, destination)
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MockWriter) MkdirAll(ctx context.Context, name string, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", ctx, name, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockWriterMockRecorder) MkdirAll(ctx, name, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockWriter)(nil).MkdirAll), ctx, name, perm)
}

// WriteFile mocks base method.
func (m *MockWriter) WriteFile(ctx context.Context, name string, data []byte, perm fs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", ctx, name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockWriterMockRecorder) WriteFile(ctx, name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockWriter)(nil).WriteFile), ctx, name, data, perm)
}

// MockRemover is a mock of Remover interface.
type MockRemover struct {
	ctrl     *gomock.Controller
	recorder *MockRemoverMockRecorder
	isgomock struct{}
}

// MockRemoverMockRecorder is the mock recorder for MockRemover.
type MockRemoverMockRecorder struct {
	mock *MockRemover
}

// NewMockRemover creates a new mock instance.
func NewMockRemover(ctrl *gomock.Controller) *MockRemover {
	mock := &MockRemover{ctrl: ctrl}
	mock.recorder = &MockRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemover) EXPECT() *MockRemoverMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockRemover) Remove(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRemoverMockRecorder) Remove(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRemover)(nil).Remove), ctx, name)
}
